name: Python Package

on:
  push:
    branches: [master]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Google Chrome
        run: |
          set -ex
          sudo apt-get update -y
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y -f

      - name: Install Chromedriver
        run: |
          sudo apt-get install -y unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.83/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv ./chrome-linux64 /usr/local/bin/
          sudo chmod +x /usr/local/bin/chrome-linux64

      - name: Install depandencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run code
        run: |
          python seek.py
