name: Python Package

on:
  push:
    branches: [master]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Google Chrome
        run: |
           sudo apt-get install -y google-chrome-stable=116.0.5845.96-1

      - name: Install Chromedriver
        run: |
          wget https://chromedriver.storage.googleapis.com/116.0.5845.96/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install depandencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run code
        run: |
          python seek.py
