name: Python Package

on:
  push:
    branches: [master]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get remove google-chrome-stable -y
          wget -N https://chromedriver.storage.googleapis.com/116.0.5845.96/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/bin/
          chmod +x /usr/bin/chromedriver
          rm chromedriver_linux64.zip
          chromedriver --version

      - name: Install depandencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run code
        run: |
          python seek.py
